// ============================================================
// Ventrify OS — Firestore data-access layer
//
// The single seam between the app and Firestore. Every page reads/writes
// engagements + org through these functions, so swapping localStorage for
// the cloud is contained here. Pure Firestore — callers decide WHEN to use
// it (FIREBASE_ENABLED + signed-in) vs the demo/localStorage fallback.
//
// Model:
//   organisations/{orgId}        { name, slug, primaryColor, logoUrl, tier }
//   engagements/{engagementId}   { orgId, founderEmail, ...program fields, brief }
//
// Single-tenant for now (ORG_ID = 'default'). When multi-org lands, ORG_ID
// becomes the signed-in user's org and the queries already filter on it.
// ============================================================

import { db } from './firebase.js';
import {
  collection, doc, getDoc, getDocs, setDoc, updateDoc, deleteDoc,
  query, where, orderBy, onSnapshot, serverTimestamp
} from 'https://www.gstatic.com/firebasejs/11.1.0/firebase-firestore.js';

export const ORG_ID = 'default';

const orgRef = () => doc(db, 'organisations', ORG_ID);
const engCol  = () => collection(db, 'engagements');
const engRef  = (id) => doc(db, 'engagements', id);

// ---- Organisation ---------------------------------------------------------
export async function getOrganisation() {
  const snap = await getDoc(orgRef());
  return snap.exists() ? { id: snap.id, ...snap.data() } : null;
}

export async function saveOrganisation(org) {
  await setDoc(orgRef(), { ...org, updatedAt: serverTimestamp() }, { merge: true });
}

// ---- Engagements ----------------------------------------------------------
// Create using the caller's id (keeps the prg-<slug>-<rand> convention and
// stable Studio URLs). Stamps orgId + timestamps.
export async function createEngagement(engagement) {
  const id = engagement.id;
  if (!id) throw new Error('createEngagement: engagement.id is required');
  await setDoc(engRef(id), {
    ...engagement,
    founderEmail: (engagement.founderEmail || '').trim().toLowerCase(),
    orgId: ORG_ID,
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp()
  });
  return id;
}

export async function getEngagement(id) {
  const snap = await getDoc(engRef(id));
  return snap.exists() ? { id: snap.id, ...snap.data() } : null;
}

// All engagements for the current org (the operator's portfolio).
export async function listEngagements() {
  const snap = await getDocs(query(engCol(), where('orgId', '==', ORG_ID)));
  return snap.docs.map(d => ({ id: d.id, ...d.data() }));
}

// Engagements a given founder owns (matched by the email on their invite).
export async function listEngagementsForFounder(email) {
  const norm = (email || '').trim().toLowerCase();
  const snap = await getDocs(query(engCol(), where('founderEmail', '==', norm)));
  return snap.docs.map(d => ({ id: d.id, ...d.data() }));
}

export async function updateEngagement(id, patch) {
  await updateDoc(engRef(id), { ...patch, updatedAt: serverTimestamp() });
}

export async function deleteEngagement(id) {
  await deleteDoc(engRef(id));
}

// Full delete: remove the engagement AND its provocation cards. Cards are
// deleted first (their delete rule reads the still-existing engagement doc),
// then the engagement. Investability snapshots, if any, are left as harmless
// orphans (clients can't delete them under the rules; nothing renders them
// once the engagement is gone). Removing the engagement makes it disappear
// from BOTH surfaces (Workspace + Studio share this Firestore).
export async function deleteEngagementDeep(id) {
  const cardsSnap = await getDocs(query(cardCol(), where('engagementId', '==', id)));
  await Promise.all(cardsSnap.docs.map(d => deleteDoc(d.ref)));
  await deleteDoc(engRef(id));
}

// Founder submits their brief → stored on the engagement, flips briefSubmitted.
export async function saveBrief(id, brief) {
  await updateDoc(engRef(id), {
    brief,
    briefSubmitted: true,
    briefSubmittedAt: serverTimestamp(),
    updatedAt: serverTimestamp()
  });
}

// ---- Live subscriptions (real-time cross-surface updates) -----------------
// cb receives the full engagement array on every change. Returns unsubscribe.
export function watchEngagements(cb) {
  return onSnapshot(query(engCol(), where('orgId', '==', ORG_ID)), (snap) => {
    cb(snap.docs.map(d => ({ id: d.id, ...d.data() })));
  });
}

export function watchEngagement(id, cb) {
  return onSnapshot(engRef(id), (snap) => {
    cb(snap.exists() ? { id: snap.id, ...snap.data() } : null);
  });
}

// ---- Provocation cards + founder responses --------------------------------
// L1 provocation cards (generated by the engagement repo's portal-publisher,
// or seeded for now). The founder responds in the Studio; the operator reads
// the response back in the Workspace. founderResponse is embedded on the card.
const cardCol = () => collection(db, 'cards');
const cardRef = (id) => doc(db, 'cards', id);

function sortCards(cards) {
  return cards.sort((a, b) => (a.hub || '').localeCompare(b.hub || '') || (a.order || 0) - (b.order || 0));
}

export async function createCard(card) {
  const id = card.id || ('card-' + Math.random().toString(36).slice(2, 10));
  await setDoc(cardRef(id), {
    level: 'L1', status: 'awaiting-founder', founderResponse: null,
    ...card,
    id, orgId: ORG_ID, createdAt: serverTimestamp(), updatedAt: serverTimestamp()
  });
  return id;
}

export async function getCard(id) {
  const snap = await getDoc(cardRef(id));
  return snap.exists() ? { id: snap.id, ...snap.data() } : null;
}

// All cards for one engagement (sorted by hub then order, client-side, so no
// composite index is needed).
export async function listCardsForEngagement(engagementId) {
  const snap = await getDocs(query(cardCol(), where('engagementId', '==', engagementId)));
  return sortCards(snap.docs.map(d => ({ id: d.id, ...d.data() })));
}

// Founder answers a card: accept / reject / reshape (+ optional comment).
export async function respondToCard(cardId, response) {
  await updateDoc(cardRef(cardId), {
    founderResponse: { decision: response.decision || 'reshape', comment: response.comment || '', respondedAt: 'just now' },
    status: 'responded',
    updatedAt: serverTimestamp()
  });
}

export async function updateCard(id, patch) {
  await updateDoc(cardRef(id), { ...patch, updatedAt: serverTimestamp() });
}

export async function deleteCard(id) { await deleteDoc(cardRef(id)); }

export function watchCardsForEngagement(engagementId, cb) {
  return onSnapshot(query(cardCol(), where('engagementId', '==', engagementId)), (snap) => {
    cb(sortCards(snap.docs.map(d => ({ id: d.id, ...d.data() }))));
  });
}

// ---- Investability snapshots (the living VSS trajectory) -------------------
// Published by the engagement repo (tools/cloud/publish.js) every time the
// operator re-scores. Ordered oldest→newest for the trajectory chart.
export async function listInvestabilitySnapshots(engagementId) {
  const col = collection(db, 'engagements', engagementId, 'investabilitySnapshots');
  const snap = await getDocs(query(col, orderBy('computedAt', 'asc')));
  return snap.docs.map(d => ({ id: d.id, ...d.data() }));
}
